/**
 * Process status constants.
 */
const PROCESS_STATUS = {
  UNSPECIFIED: 'UNSPECIFIED',
  STARTED: 'STARTED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  INTERRUPTED: 'INTERRUPTED'
};

export default PROCESS_STATUS;
